### ISSUE TITLE
Truffle test doesn´t work

### ISSUE THREAD

**Issue by BrunoAl25** [randao/randao#22]
Hi. I did a test using truffle v4.0.7 and Ganache and the following error occurred:

 1 passing (4s)
  3 failing

  1) Contract: Randao randao campaign lifecycle:
     TypeError: counter.count is not a function
      at Object.ff (test\helper\timecop.js:15:24)
      at Randao.deployed.then.then.then.then (test\randao.js:37:22)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  2) Contract: Randao randao campaign lifecycle:
     TypeError: counter.count is not a function
      at Object.ff (test\helper\timecop.js:15:24)
      at Randao.deployed.then.then.then.then (test\refundBounty.js:35:22)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  3) Contract: Timecop fast forward fast forward 3 blocks:
     TypeError: counter.count is not a function
      at Object.ff (test\helper\timecop.js:15:24)
      at Context.it (test\timecop.js:8:13)

**Comment by u2** [comment]
Now just works with Truffle v2.1.0, welcome PR.

**Comment by u2** [comment]
#27
